 slam_toolbox:
  ros__parameters:
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "scan"
    use_sim_time: true
    publish_map_transform: true
    localization_mode: false
